### ISSUE TITLE
Connection to postgresql

### ISSUE THREAD

**Issue by evolv34** [jjethwa/rundeck#125]
Hi, 

I am using rundeck container. I would like to use postgresql to store rundeck project information. Does the current version supports postgresql ? Where should I place the postgres jdbc driver ?

```rundeck:
    image: jordan/rundeck:latest
    ports: 
      - "4440:4440"
    links:
      - database:database
    environment:
      SKIP_DATABASE_SETUP: "false"
      NO_LOCAL_MYSQL: "true"
      DATABASE_URL: jdbc:postgres://database/rundeckdb?autoReconnect=true
      DATABASE_ADMIN_USER: admin
      DATABASE_ADMIN_PASSWORD: admin
      RUNDECK_STORAGE_PROVIDER: db
      #RUNDECK_PROJECT_STORAGE_TYPE: db

  database:
    image: postgres:10.3
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'rundeckdb'```

This is my docker compose file. Can you please help ?

**Comment by jjethwa** [comment]
Hi @evolv34 

The postgres driver is included in the default Rundeck install.  I have not tested the container with a postgres backend though and the /opt/run script does not handle postgres yet 😢  You would need to follow the directions for creating the database and user: http://rundeck.org/docs/administration/setting-up-an-rdb-datasource.html#postgresql-setup-guide and also set dataSource.driverClassName in the rundeck-config.properties file

It should not take too much work to add postgres handling in /opt/run but I'll be away for the next two weeks or so.

**Comment by evolv34** [comment]
Thanks jjethwa, I will try it out.

**Comment by jjethwa** [comment]
NP!  I'll work on the updates when I get back or feel free to submit a PR if you have time 😄

**Comment by evolv34** [comment]
Sure

**Comment by evolv34** [comment]
Hi @jjethwa,

I have created a pull request for this issue. Currently it supports external postgres. 
https://github.com/jjethwa/rundeck/pull/126

**Comment by evolv34** [comment]
```
version: '2.1'

services: 
  rundeck:
      image: <rundeck image name>
      hostname: rundeck
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:4440/menu/home"]
        interval: 50s
        timeout: 30s
        retries: 3
      depends_on:
        postgres:
          condition: service_healthy
      links:
        - postgres:postgres
      ports:
        - "4441:4440"
      environment:
        EXTERNAL_SERVER_URL: http://localhost:4440
        SKIP_DATABASE_SETUP: "false"
        NO_LOCAL_MYSQL: "true"
        DATABASE_DRIVER: org.postgresql.Driver
        DATABASE_URL: jdbc:postgresql://postgres/rundeckdb
        DATABASE_ADMIN_USER: admin
        RUNDECK_PASSWORD: admin
        RUNDECK_STORAGE_PROVIDER: db


  postgres:
    image: postgres
    hostname: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - '5433:5432'
    # volumes:
    #   - ./test-data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'postgres'
```
I used this yml file for testing. Hope its helpful
